### ISSUE TITLE
GPT-2 example from README.md not working. (BS=1)

### ISSUE THREAD

**Issue by philschmid** [aws-neuron/transformers-neuronx#13]
Hello, the example code snippet from the Readme.md is not working. 

```python
import os
from transformers_neuronx.gpt2.model import GPT2ForSampling
from transformers_neuronx.generation_utils import HuggingFaceGenerationModelAdapter
from transformers_neuronx.module import save_pretrained_split
from transformers import AutoModelForCausalLM, AutoTokenizer
os.environ['NEURON_CC_FLAGS'] = '--model-type=transformer-inference'

# Load and save the CPU model
model_cpu = AutoModelForCausalLM.from_pretrained('gpt2')
save_pretrained_split(model_cpu, 'gpt2-split')

# Create and compile the Neuron model
model = GPT2ForSampling.from_pretrained('gpt2-split', batch_size=1, tp_degree=2, n_positions=256, amp='f32', unroll=None)
if hasattr(model, 'register_to_neuron_hook'):
    model.register_to_neuron_hook(lambda idx: print(f'done to_neuron layer {idx}'))
print('running model.to_neuron')
model.to_neuron()
```

Error: 

```
running model.to_neuron
.2023-06-29T11:57:55Z ERROR 2975 [WalrusDriver]: An exception was thrown:
--------------------------------------------------------------------------------
 0# __cxa_throw in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libwalrus.so
 1# 0x00007FB8EC7EDE96 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libBIRVerifier.so
 2# birverifier::checkInputMemType(bir::Instruction const&, unsigned int, llvm::SmallVector<bir::MemoryType, 3u> const&) in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libBIRVerifier.so
 3# birverifier::InstVisitor::visitInstIndirectSave(bir::InstIndirectSave&) in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libBIRVerifier.so
 4# neuronxcc::walrus::Verifier::run(bir::Module&) in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libwalrus.so
 5# neuronxcc::walrus::WalrusPass::run(std::vector<std::unique_ptr<bir::Module, std::default_delete<bir::Module> >, std::allocator<std::unique_ptr<bir::Module, std::default_delete<bir::Module> > > >&) in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libwalrus.so
 6# 0x00007FB8E53763FE in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libwalrus.so
 7# run_walrus_driver(int, char**) in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/../../../starfish/lib/libwalrus.so
 8# 0x00007FB8EC82F130 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/support/EmbeddedWalrusDriver.cpython-38-x86_64-linux-gnu.so
 9# 0x00007FB8F5308820 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/WalrusDriver.cpython-38-x86_64-linux-gnu.so
10# 0x00007FB8F531335E in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/WalrusDriver.cpython-38-x86_64-linux-gnu.so
11# _PyObject_MakeTpCall in /usr/bin/python3
12# _PyObject_FastCallDict in /usr/bin/python3
13# _PyObject_Call_Prepend in /usr/bin/python3
14# 0x00007FB8F53069EC in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/WalrusDriver.cpython-38-x86_64-linux-gnu.so
15# 0x00007FB8F532871E in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/WalrusDriver.cpython-38-x86_64-linux-gnu.so
16# _PyObject_MakeTpCall in /usr/bin/python3
17# _PyObject_FastCallDict in /usr/bin/python3
18# _PyObject_Call_Prepend in /usr/bin/python3
19# 0x00007FB90C49FC3C in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
20# 0x00007FB90C4B42D6 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
21# _PyObject_MakeTpCall in /usr/bin/python3
22# _PyObject_FastCallDict in /usr/bin/python3
23# _PyObject_Call_Prepend in /usr/bin/python3
24# 0x00007FB90C49FC3C in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
25# 0x00007FB90C4AFAC8 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
26# 0x00007FB8F531CBE2 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/jobs/WalrusDriver.cpython-38-x86_64-linux-gnu.so
27# _PyObject_MakeTpCall in /usr/bin/python3
28# _PyObject_FastCallDict in /usr/bin/python3
29# _PyObject_Call_Prepend in /usr/bin/python3
30# 0x00007FB90C4CCC6B in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Pipeline.cpython-38-x86_64-linux-gnu.so
31# 0x00007FB90C4CF082 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Pipeline.cpython-38-x86_64-linux-gnu.so
32# _PyObject_MakeTpCall in /usr/bin/python3
33# _PyObject_FastCallDict in /usr/bin/python3
34# _PyObject_Call_Prepend in /usr/bin/python3
35# 0x00007FB90C49FC3C in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
36# 0x00007FB90C4B42D6 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
37# _PyObject_MakeTpCall in /usr/bin/python3
38# _PyObject_FastCallDict in /usr/bin/python3
39# _PyObject_Call_Prepend in /usr/bin/python3
40# 0x00007FB90C49FC3C in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
41# 0x00007FB90C4AFAC8 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/Job.cpython-38-x86_64-linux-gnu.so
42# _PyObject_MakeTpCall in /usr/bin/python3
43# _PyObject_FastCallDict in /usr/bin/python3
44# _PyObject_Call_Prepend in /usr/bin/python3
45# 0x00007FB90BF52ECC in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/commands/CompileCommand.cpython-38-x86_64-linux-gnu.so
46# 0x00007FB90BF8ABA9 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/commands/CompileCommand.cpython-38-x86_64-linux-gnu.so
47# _PyObject_MakeTpCall in /usr/bin/python3
48# _PyObject_FastCallDict in /usr/bin/python3
49# _PyObject_Call_Prepend in /usr/bin/python3
50# 0x00007FB90BF58CD1 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/commands/CompileCommand.cpython-38-x86_64-linux-gnu.so
51# _PyObject_MakeTpCall in /usr/bin/python3
52# _PyObject_FastCallDict in /usr/bin/python3
53# _PyObject_Call_Prepend in /usr/bin/python3
54# 0x00007FB90C5A079C in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/CommandDriver.cpython-38-x86_64-linux-gnu.so
55# 0x00007FB90C5AC9AA in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/CommandDriver.cpython-38-x86_64-linux-gnu.so
56# _PyObject_MakeTpCall in /usr/bin/python3
57# _PyObject_FastCallDict in /usr/bin/python3
58# _PyObject_Call_Prepend in /usr/bin/python3
59# 0x00007FB90C5A2CED in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/CommandDriver.cpython-38-x86_64-linux-gnu.so
60# 0x00007FB90C5A2EC2 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/CommandDriver.cpython-38-x86_64-linux-gnu.so
61# 0x00007FB90C5B5DA2 in /usr/local/lib/python3.8/dist-packages/neuronxcc/driver/CommandDriver.cpython-38-x86_64-linux-gnu.so
62# _PyObject_MakeTpCall in /usr/bin/python3
63# _PyEval_EvalFrameDefault in /usr/bin/python3
64# _PyEval_EvalCodeWithName in /usr/bin/python3
65# PyEval_EvalCode in /usr/bin/python3
66# 0x0000000000680001 in /usr/bin/python3
67# 0x000000000068007F in /usr/bin/python3
68# 0x0000000000680121 in /usr/bin/python3
69# PyRun_SimpleFileExFlags in /usr/bin/python3
70# Py_RunMain in /usr/bin/python3
71# Py_BytesMain in /usr/bin/python3
72# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
73# _start in /usr/bin/python3
--------------------------------------------------------------------------------
2023-06-29T11:57:55Z ERROR 2975 [WalrusDriver]: Walrus pass: birverifier failed!
2023-06-29T11:57:55Z ERROR 2975 [WalrusDriver]: Failure Reason: === BIR verification failed ===
Reason: Expect memory location to be of type SB 
Instruction: I-10873
Opcode: IndirectSave
Input index: 1
Argument AP:
Access Pattern: [[384,1],[384,1],[1,64]]
SymbolicAP
Memory Location: {_reshape_273_hlo_id_2756__mhlo.reshape_20_pftranspose_5301-t9595_set}@PSUM
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: ***************************************************************
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:  An Internal Compiler Error has occurred
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: ***************************************************************
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: 
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: Error message:  Walrus driver failed to complete
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: 
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: Error class:    AssertionError
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: Error location: Unknown
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: Command line:   /usr/local/bin/neuronx-cc compile --framework=XLA --target=trn1 /tmp/tmpkbnmkhnd/FullyUnrolled.1826.1.pb --output=/tmp/tmpkbnmkhnd/FullyUnrolled.1826.1.pb.neff --verbose=35 --model-type=transformer-inference
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: 
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: Internal details:
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/CommandDriver.py", line 237, in neuronxcc.driver.CommandDriver.CommandDriver.run
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1047, in neuronxcc.driver.commands.CompileCommand.CompileCommand.run
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 998, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1023, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1027, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 300, in neuronxcc.driver.Job.SingleInputJob.run
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 326, in neuronxcc.driver.Job.SingleInputJob.runOnState
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/Pipeline.py", line 30, in neuronxcc.driver.Pipeline.Pipeline.runSingleInput
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/jobs/WalrusDriver.py", line 232, in neuronxcc.driver.jobs.WalrusDriver.WalrusDriver.run
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 300, in neuronxcc.driver.Job.SingleInputJob.run
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 326, in neuronxcc.driver.Job.SingleInputJob.runOnState
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   File "neuronxcc/driver/jobs/WalrusDriver.py", line 702, in neuronxcc.driver.jobs.WalrusDriver.WalrusDriver.runSingleInput
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: 
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: Version information:
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   NeuronX Compiler version 2.5.0.28+1be23f232
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   HWM version 2.5.0.0-dad732dd6
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   NEFF version Dynamic
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   TVM not available
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   NumPy version 1.21.6
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]:   MXNet not available
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: 
2023-06-29T11:57:55Z ERROR 2975 [neuronx-cc]: Artifacts stored in: /tmp/tmpkbnmkhnd/neuronxcc-9vjdmvs0

Compiler status ERROR
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model.to_neuron()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/gpt2/model.py", line 117, in to_neuron
    self.decoder_lm_head.to_neuron()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 107, in to_neuron
    self.program.setup(self.layers, ln_lm_head_params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 792, in setup
    super().setup(layers, ln_lm_head_params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 747, in setup
    kernel.build()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/compiler.py", line 287, in build
    self.neff_bytes = compile_hlo_module(self.hlo_module)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers_neuronx/compiler.py", line 71, in compile_hlo_module
    subprocess.check_call(command_line, cwd=tmpdir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['neuronx-cc', 'compile', '--framework=XLA', '--target=trn1', '/tmp/tmpkbnmkhnd/FullyUnrolled.1826.1.pb', '--output=/tmp/tmpkbnmkhnd/FullyUnrolled.1826.1.pb.neff', '--verbose=35', '--model-type=transformer-inference']' returned non-zero exit status 1.
```

**Comment by philschmid** [comment]
FYI. Running the sample with a `batch_size=2` works.

**Comment by aws-ennst** [comment]
Hi @philschmid. We have reproduced the issue and have a fix which will be available in an upcoming release.

**Comment by aliseyfi** [comment]
Hi @aws-ennst any updates on this?

**Comment by dacorvo** [comment]
Can you confirm this is fixed with latest release ?

**Comment by aliseyfi** [comment]
> Can you confirm this is fixed with latest release ?

This is working for me with `batch_size=2` and `tp_degree=4`. tp_degree should be a divisor of number of attention heads, just fyi.

**Comment by jeffhataws** [comment]
Hi @dacorvo , I have confirmed that the GPT-2 code snippet from README.md is now working with release 2.11:

```
(aws_neuron_venv_pytorch) ubuntu@ip-10-0-10-149:~$ python test.py
.
Compiler status PASS
.
Compiler status PASS
Downloading (…)olve/main/vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 64.1MB/s]
Downloading (…)olve/main/merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 38.3MB/s]
Downloading (…)/main/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 34.0MB/s]
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
['Hello, I\'m a language model, you know. So I\'ll give you an example.\n\nNow this is really important, and you know: if you\'re a programmer, you\'re going to have to understand these things. I don\'t mean programming, or programming about languages. I mean writing. And so the first thing I need to do is write a program for the program, and then I need to write a function. And that\'s a lot of stuff, and it\'s not something that you could just throw away.\n\nThen you don\'t have to write a compiler. You can write a language, and you can write a function, and they\'ll look at your code and say, "Okay, this is going to be a function."\n\nNow, because languages are so powerful, and because they\'re so complicated, if it\'s a function, then you can write a function, and you\'re going to be able to write a function, and you\'re going to be able to write a function. And so that\'s a big problem, and it\'s one that\'s really hard to fix.\n\nSo the first thing I need to do is write a program. And then I need to write a function, and I need to write']
```

Packages:
```
(aws_neuron_venv_pytorch) ubuntu@ip-10-0-10-149:~$ pip list | grep neuron
aws-neuronx-runtime-discovery 2.9
libneuronxla                  0.5.391
neuronx-cc                    2.8.0.25+a3ad0f342
neuronx-distributed           0.1.0
neuronx-hwm                   2.8.0.3+2b7c6da39
torch-neuronx                 1.13.1.1.9.0
torch-xla                     1.13.1+torchneuron8
transformers-neuronx          0.5.58
```
