### ISSUE TITLE
Fail to install transformers-neuronx

### ISSUE THREAD

**Issue by draftbk** [aws-neuron/transformers-neuronx#19]
Hi I am trying to run a demo from triton:https://github.com/triton-inference-server/python_backend/tree/main/inferentia on an `inf2.24xlarge` instance.  

Here are the command lines to reproduce the issue:
```
# Start a docker on the inf2.24xlarge instance
sudo docker run --shm-size=2g -it nvcr.io/nvidia/tritonserver:23.04-py3 

# Run this command in the started docker
pip3 install transformers-neuronx --extra-index-url=https://pip.repos.neuron.amazonaws.com
```
The error message:
```
root@69eded59b438:/opt/tritonserver# pip3 install transformers-neuronx --extra-index-url=https://pip.repos.neuron.amazonaws.com
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Collecting transformers-neuronx
  Downloading https://pip.repos.neuron.amazonaws.com/transformers-neuronx/transformers_neuronx-0.4.60-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 26.3 MB/s eta 0:00:00
Collecting accelerate (from transformers-neuronx)
  Downloading accelerate-0.21.0-py3-none-any.whl (244 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.2/244.2 kB 30.0 MB/s eta 0:00:00
Collecting torch-neuronx (from transformers-neuronx)
  Downloading https://pip.repos.neuron.amazonaws.com/torch-neuronx/torch_neuronx-1.13.1.1.8.0-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 62.8 MB/s eta 0:00:00
Collecting transformers (from transformers-neuronx)
  Downloading transformers-4.30.2-py3-none-any.whl (7.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 127.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from accelerate->transformers-neuronx) (1.24.2)
Collecting packaging>=20.0 (from accelerate->transformers-neuronx)
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 16.7 MB/s eta 0:00:00
Collecting psutil (from accelerate->transformers-neuronx)
  Downloading psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.1/282.1 kB 67.8 MB/s eta 0:00:00
Collecting pyyaml (from accelerate->transformers-neuronx)
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 701.2/701.2 kB 92.8 MB/s eta 0:00:00
Collecting torch>=1.10.0 (from accelerate->transformers-neuronx)
  Downloading torch-2.0.1-cp38-cp38-manylinux1_x86_64.whl (619.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 2.1 MB/s eta 0:00:00
  Downloading torch-1.13.1-cp38-cp38-manylinux1_x86_64.whl (887.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.4/887.4 MB 1.5 MB/s eta 0:00:00
Collecting torch-xla==1.13.1+torchneuron7 (from torch-neuronx->transformers-neuronx)
  Downloading https://pip.repos.neuron.amazonaws.com/torch-xla/torch_xla-1.13.1%2Btorchneuron7-cp38-cp38-linux_x86_64.whl (267.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.7/267.7 MB 7.1 MB/s eta 0:00:00
Collecting libneuronxla==0.5.326 (from torch-neuronx->transformers-neuronx)
  Downloading https://pip.repos.neuron.amazonaws.com/libneuronxla/libneuronxla-0.5.326-py3-none-linux_x86_64.whl (52.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.9/52.9 MB 35.3 MB/s eta 0:00:00
Collecting protobuf<5 (from torch-neuronx->transformers-neuronx)
  Downloading protobuf-4.23.4-cp37-abi3-manylinux2014_x86_64.whl (304 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.5/304.5 kB 66.3 MB/s eta 0:00:00
Collecting aws-neuronx-runtime-discovery~=2.0 (from libneuronxla==0.5.326->torch-neuronx->transformers-neuronx)
  Downloading https://pip.repos.neuron.amazonaws.com/aws-neuronx-runtime-discovery/aws-neuronx-runtime-discovery-2.9.tar.gz (1.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-23z1w1bc/aws-neuronx-runtime-discovery_74fefbd0a1fd4c4f986415e84c123c5f/setup.py", line 46, in <module>
          main()
        File "/tmp/pip-install-23z1w1bc/aws-neuronx-runtime-discovery_74fefbd0a1fd4c4f986415e84c123c5f/setup.py", line 15, in main
          raise FileNotFoundError('Could not find Neuron Runtime Library {} (from deb/rpm package aws-neuronx-runtime-lib) in {}. Please check {} to install this library.'.format(soname_path, libnrt_installation_path, guide_link))
      FileNotFoundError: Could not find Neuron Runtime Library /opt/aws/neuron/lib/libnrt.so.1 (from deb/rpm package aws-neuronx-runtime-lib) in /opt/aws/neuron/lib. Please check the Neuron installation guide https://awsdocs-neuron.readthedocs-hosted.com/ to install this library.
      2.9
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by aws-taylor** [comment]
Hello @draftbk,

  The `transformer-neuronx` python package requires that the AWS Neuron Runtime Library be installed. This is vended separately as an .deb/.rpm package in our repositories. You can find instructions for how to install the library here - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/index.html#setup-guide-index
  
  Please let me know if you need additional assistance.
  
Regards,
Taylor

**Comment by draftbk** [comment]
Hi Taylor,

Thanks for your response!

And I finally tried to run this .sh file to resolve this issue: https://github.com/triton-inference-server/python_backend/blob/main/inferentia/scripts/setup.sh 

I think inside that file there are steps to stall the  AWS Neuron Runtime as you mentioned. 


Thanks!
draftbk
